# Introduction

## Structure of the Senior Comprehensive Project

This report is divided into five chapters. Chapter One discusses the key contributions of MakeUp, its improvements on similar projects, and MakeUp's ability to address ethical concerns. Chapter Two explores relevant literature and connects it to the research conducted for this project. Chapter Three explains the research process, the development of MakeUp, the design of experiments, and the tools used in this project. Chapter Four illustrates the results of the MakeUp experiment and any problems that were found within the experiment. Finally, Chapter Five summarizes and discusses the findings of this project and shines a light upon the significance of the actions taken to finalize MakeUp. This structure helps provide clarity and fluidity to this report.

## Background and Motivations

This project addresses the problem of creative burnout and lack of motivation for both starting and finishing creative projects. Many are frustrated with their perceived inability to finish projects or feel overwhelmed by the prospect of some ideas that seem too large. Others find it difficult to begin projects in the first place, pointing to a lack of ideas, motivation, a fear of failure and intimidation (among other reasons). MakeUp is an app that provides users with bite-sized creative prompts and a competition system in order to encourage users to both start smaller novel projects and to encourage users to consistently finish projects that motivate them to continue creating rather than uninstalling the app or quitting creative projects altogether.

It has been found that a moderate level of competition can increase both creative productivity and originality (@Gross2020). If a creative actor has is faced with a challenge that they perceive as too difficult, they will abandon the project that they were going to produce, meaning that this creative work will never be shared with the rest of the world. If the competition is perceived as too easy, however, the subject will not be motivated to create a project with a high degree of originality. Because of the low bar set by low competition, much of competitors' output will be very similar to each other. MakeUp features a dynamic competition system that adapts to the user's level of creative activity. If a user is consistently submitting projects and collecting higher point totals per day and week, the competition will increase in difficulty in order to motivate the user to continue completing prompts in the app. If a user is struggling to submit projects regularly due to time constraints or lack of motivation, or uninstalled the app but is reinstalling it during a burst of motivation, the competition will ease the user into the app by providing a less punishing competitive environment. This will hopefully discourage users from uninstalling the app within a day or two, pushing their motivational satellite into an orbit rather than a crash to the ground (only to be launched unsuccessfully again at a later date).

MakeUp also is designed to help the user form habits when tackling creative projects by emphasizing convenience. Apps are a unique tool in that they are readily available for a large portion of the population. About 91% of Americans own a smartphone, including about 96% of American adults under 50 years of age (@SmartphoneOwnership). Apps are accessible to most to use in the first place and are also staring users in the face when they record their average screen time of roughly 5 hours per day (@Alam2023). Conveniency is king when forming habits: businesses that have launched mobile apps have generally seen an increase in their sales figures due to the formation of habitual interaction with brands (@VanHeerde2019). The potential for apps to help users form desired habits is also evident for students. Students who used a mobile app to intentionally track their habits over just 6 weeks were able to significantly increase the automaticity of their desired behaviors as well as limit their motivational impairments (@Stojanovic2020). It is clear that an app is one of the most powerful tools that could be implemented to help users form habits; MakeUp uses the convenience of app accessibility and visibility in order form patterns of consistent creative output.

## Overview of MakeUp

MakeUp is an android application that uses a point system and prompts to encourage users to submit bite-sized creative projects to the app every day. Users are given three daily prompts at midnight each day: a one-point, two-point and three-point prompt (the amount of points should correlate roughly to the time commitment required for a project). The user can choose one of the three prompts each day to complete and submit to the app. These prompts should be able to be completed in a short amount of time; one-point prompts should be completable in about 10 minutes, two-point prompts in about 20 minutes, and three-point prompts in about 30 minutes. Prompt submissions are uploaded to the user's profile page, which displays all past file and text submissions so that the user can see tangible results. Users who can more easily see the measurable progress that they have made using the app will be more likely to gain a positive perception of their work (@Amabile2007).

Similarly, users are able to complete a weekly prompt that is submitted to their profile page. The difference, however, is that rather than the weekly prompt being assigned each week, the user is required to submit their own prompt or goal to the app and assign it its own point value (capped at 15 points). This allows users who benefit more from a journaling workstyle to set their own goals and track their progress through the profile page, which displays both completed weekly prompts and past weekly prompt ideas that were never finished. The weekly prompt also safeguards users from an overreliance on prompts which are not original to them. While the daily prompts can be a great source of inspiration and helpful for bite-sized projects, the trade-off is that users may not diverge much from what they see others doing for similar projects because the base idea for the project is not their own. Additionally, the daily prompt is limited in that the user may not necessarily love the three ideas that they are given each day. The weekly prompt gives users an outlet to create their own projects from scratch and explore more niche projects that may not be included in the app's daily prompts (both on a specific day or generally). Summarized, the daily prompt is a powerful tool for kickstarting the creative process and providing inspiration for more easily completable projects with quickly visible results, while the weekly prompt should be harnessed to provide flexibility within the app's experience and to encourage users to flex their creative muscles in a more personal way.

The component of the app that helps to motivate users in their quest for increased creative output is the "League" system. Users are placed on a leaderboard with rival non-human competitors. The user then accumulates points over a four week period or "season" by completing daily and weekly prompts. This accumulation of points or lack therof causes the user to rise or fall on the leaderboard. Competitors also move up and down the leaderboard based on a combination of the difficulty in the app settings, random chance, and, most importantly, the user's consistency of submission to the app. Competitor difficulty adjusts based on the user's upload rates at a given time so that users who are submitting projects consistently will be faced with a larger challenge and users whose consistency are waning or those who are just starting out will be eased into the competition. The goal is to minimize the feeling of overwhelming competition while still providing a moderate level of competition that does not feel too easy.

If a user places above a certain threshold on the leaderboard at the end of the four-week league period, they will be promoted to a higher rank. If they place below a certain threshold, they will be relegated to a lower rank. These ranks help the user to always have something to work towards rather than just finishing a league and saying "I won!" and uninstalling the app. The ranks also help give the user a long-term feeling of progress that they can measure and observe over time.

The user has many experience customization options throughout the app (especially in their settings, which can be found through the profile page). Users can manually change the difficulty of the competition if they find the dynamic competition feature too easy or difficult. They can also change the duration of league to something other than four weeks, as well as changing the amount of competitors. They can alter their username and logo, which will appear on both their profile screen and league screen. Similarly, they can change the logo and name of every competitor in their league. Finally, users can change the color scheme of the app to a color other than yellow. These customization options helps the user feel more at home within the MakeUp experience.

## Improving on Similar Tools and the State of Competition for Habit-Building

Gamification of a habit or action is not an especially new idea. Popular apps like Duolingo and Habitica have all implemented competitive elements in an attempt to aid others in learning a new language, forming habits and learning to play an instrument, respectively. MakeUp is similar to these apps in that it also uses gamification to encourage users to form habits and complete projects, but it also aims to improve on some major flaws faced by each of these apps.

### Duolingo

Duolingo is probably the most successful app to compare MakeUp to regarding its gamification approach. It has an extremely large user base (50 million daily active users) and is the most popular language learning app that exists right now. Duolingo's strengths lie in its ability to ease users into the experience and help users to not feel overwhelmed by the large scale of learning a new language. Another strength of Duolingo is its competition system, which is implemented to help motivate users by providing dopamine boosts through the user's rising through the leaderboards.

There are significant problems, however, with Duolingo's competition system. Because the tournaments are exclusively real people competing against other real people, it is difficult to help casual users progress through the ranks. This can make users feel consistently defeated without getting the dopamine boost of winning (because they're not). Leagues can also feel unfair to both users who are starting out and users who are consistently using the app because of the lack of seperation of languages in the leagues. An English-speaking user who is learning Japanese, for example, will be put in a league with users who are learning Spanish, which is considered a much easier language for English speakers to learn (@Languages).

MakeUp's competition system address these issues by implement non-human competitors which adapt to the user's level of activity. This dynamic experience offers casual users the opportunity to still feel a sense of accomplishment while keeping them engaged with the app. The removal of living competitors also levels the playing field by introducing controllable opposition. If the dynamic competition feels too easy or difficult, the user may personalize their league experience by setting a flat difficulty that may be higher or lower depending on their desired degree of struggle.

### Habitica

Habitica is an app that encourages users to form routines and establish practices by gamifying the process of habit formation. Users are able to create their own habits and assign them point values similarly to the weekly prompt function in MakeUp. Users then earn points for completing their habits and can use those points to buy rewards or to compete with other users in a guild (a group of users that band together). Completing tasks also generates XP and helps complete RPG-style missions. This offers competition with both real life users and NPC opponents.

There are some significant problems with Habitica's approach to gamification however. Habitica's progress is measured in character levels, which means that the actual habit accomplishments are too bitesized to be a primary source of motivation within the app. Because of this, progress can feel slow if you are completing the habits you wanted to build, but you didn't level up that day or even that week. Additionally, Habitica can be very overwhelming from a features standpoint. Because the app is structured similarly to an RPG, there are a plethora of items, missions and tasks to complete. This can be a good thing if a user is experienced with the game, but can also provide a steep learning curve for new users and can make the app feel overwhelming and difficult to navigate. The amount of time spent maximizing the XP or resources needed for specific missions and deciding which items to purchase can distract from the actual habit-building part of the game.

The app can overwhelm the user, but so can the user themselves. Because there is no limit on the amount of tasks or habits that a user gives themselves, users can spend a lot of time and effort just creating and monitoring their own challenges. This creates a crowded atmosphere on the screen and causes tasks that user finds less important or motivating to distract from the habits that the user initially installed the app in order to build.

MakeUp solves all of these problems by implementing a minimalistic design that is as user-friendly as possible, setting healthy limits on daily use, and making daily accomplishments feel meaningful every single day that the user interacts with the app. MakeUp's pastel yellow and brown design features a large amount of negative space and simple elements, allowing the user to focus on their prompts without being distracted by an overcrowded layout. Additionally, users are limited to one daily prompt per day and one weekly prompt per week, preventing the user from overloading themselves with tasks and habits that they may not be motivated to complete. It should never feel like a burden to open the app and be greeted by an overwhelming amount of work to do; rather, the app should be opened, it should help the user with a bite-sized task, and then it should be closed. The focus is meant for the tasks and habits rather than an immense amount of distractions. Daily accomplishments feel meaningful due to the aformentioned limit on daily submissions and also the fact that a stepping stone is provided every single day. Because there is a single task per day, it both provides a greater meaning to the completion of a task and also helps moderate the user's ability to overwhelm themselves.

## Ethical Implications

With any new tool, there are potential ethical implications that should be considered. Submission-based tools specifically have to be concerned about users' data and privacy rights. MakeUp will be entirely local, so creative projects will not be stored in a location where anyone other than the owner of the device on which MakeUp is installed could see their data. Additionally, MakeUp does not require any data to be collected from the user regarding personal details; the most personal that MakeUp could get is the user's file uploads and username preference. This will mitigate privacy concerns and the potential misuse of data.

Another potential concern is the addictive nature that some apps can possess. Everytime a goal is accomplished, dopamine is released and the brain is trained to recreate that feeling. Without any limits on usage, players could develop an unhealthy relationship with the app. This could also dilute the impact of completing a task because of the quantity of tasks completed each day. In order to prevent this, a once-per-day limit has been placed on the user's daily submission capabilities. This submission cap will help combat obsessions with the app and also will make user's more satisfied with the submission of each task, helping users want to come back to the app each day so as to encourage consistent creative output while maintaining a healthy relationship with the app.

An alternate form of overreliance could be found in the user's dependence on MakeUp's creativity prompts. Though MakeUp's daily prompts offer inspiration to those who are struggling to start projects or are unaware of some niche creativity categories, users could also bank too heavily on the specific prompts given by MakeUp in order to develop creative ideas. This could potentially lead to a loss of some originality because the base idea was not created by the user. This problem is addressed by the weekly prompt. Users may create their own prompt to be completed over the course of a week and assign a point value to that prompt that they consider reasonable. This allows the user to begin the creative process with their own idea and also offers greater flexibility to users who may not be interested in some of the daily prompts they've been given. The daily prompt database is also extremely expansive in order to give the users as diverse of a base idea as possibleThe weekly prompt solves the overreliance problem while still allowing the daily prompts to exist and inspire users to complete projects.

A common critique of apps that use gamification are their potential to create toxic competitive environments. If the competition is too intense, users may feel defeated and unmotivated. This can also lead to higher ranked players being considered "better" than lower ranked players. Users may feel pressured to perform better than other real-life app members, which could lead to unhealthy competition and resentment between users. This also leaves no room for casual participants in the MakeUp experience. Ultimately, MakeUp's objective is self-help rather than a focus on comparisions with other users. This is why MakeUp will contain no human competition element until a healthy way of implementing it is discovered. Instead, non-human competitors will take its place, offering easily-controllable competition that minimizes toxicity in MakeUp's environment.

