name: Introduction review (Junior Seminar)
description: Provide peer review feedback for the Introduction chapter of this junior seminar research project.
title: "Spring 2026 Introduction Peer Review"
body:
  - type: markdown
    attributes:
      value: |
        Please respond to the following questions about the introduction chapter.
  - type: checkboxes
    attributes:
      label: Project clarity
      description: After reading the first two paragraphs of the introduction, I can clearly articulate a broad summary of the research project.
      options:
        - label: "Yes"
        - label: "No"
  - type: textarea
    attributes:
      label: Project clarity description
      description: In your own words, provide a description of the main area being researched and the role that this project plays.
  - type: checkboxes
    attributes:
      label: Project background
      description: The writing presents a broad, reasonably comprehensive set of background information such that readers are convinced of the relevance and significance of the project's intended contribution/intervention in the subject/field.
      options:
        - label: "Yes"
        - label: "No"
  - type: checkboxes
    attributes:
      label: Project definitions, terminology
      description: The author clearly defines all terms not generally part of common knowledge (i.e., I can describe or understand all jargon or discipline-/problem- specific language in the introduction).
      options:
        - label: "Yes"
        - label: "No"
  - type: checkboxes
    attributes:
      label: Project assumptions, limitations, delimitations
      description: The author's constraining/guiding assumptions and limiations are clearly defined and discussed (not merely mentioned).
      options:
        - label: "Yes"
        - label: "No"
  - type: textarea
    attributes:
      label: Project assumptions description
      description: What key assumptions are not addressed or addressed very little? What other disclaimers about project scope should the writer include?
  - type: checkboxes
    attributes:
      label: Project ethics
      description: The author substantively discusses more than two (2) ethical issues that the project presents or addreses.
      options:
        - label: "Yes"
        - label: "No"
  - type: textarea
    attributes:
      label: Project ethics description
      description: What additional ethical areas did the author not include? What challenges need more definition?
  - type: checkboxes
    attributes:
      label: Project sourcing
      description: The author cites sources in the introduction.
      options:
        - label: "Yes"
        - label: "No"
  - type: textarea
    attributes:
      label: General Introduction feedback
      description: "Highlight 3 areas (excluding grammar) that the author should develop further. Include: one minor, one moderate, and one major revision area."
