---
name: Final Instructor Feedback (Junior Seminar)
about: Provide final instructor feedback for a student's junior seminar research report.
title: "Final Instructor Feedback"
label: 'enhancement'
---

The following categories provide feedback for you to complete at three levels:

- `YOU MUST`: revisions of high significance which affect your ability to pass the Junior Seminar course
- `YOU SHOULD`: revisions of moderate significance which influence your grade in the course at the whole letter grade level
- `YOU COULD`: revision of minor significance which may raise your grade by a half a letter or are future considerations

## You Must

- Item 1
- Item 2

## You Should

- Item 1
- Item 2

## You Could

- Item 1
- Item 2
